apiVersion: apps/v1
kind: Deployment
metadata:
  name: a3028-blue             # 이름 다르게!
spec:
  replicas: 3                  # 그림처럼 3개 띄워봅시다
  selector:
    matchLabels:
      app: a3028-zero-dtd-test
      version: 1.0.0           # [핵심] 버전 1.0.0
  template:
    metadata:
      labels:
        app: a3028-zero-dtd-test
        version: 1.0.0
    spec:
      containers:
      - name: a3028-app
        image: amdp-registry.skala-ai.com/skala26a-ai1/a3028-my-app:latest
        ports:
        - containerPort: 8080