apiVersion: apps/v1
kind: Deployment
metadata:
  name: a3028-green            # 이름 다르게!
spec:
  replicas: 3
  selector:
    matchLabels:
      app: a3028-zero-dtd-test
      version: 2.0.0           # [핵심] 버전 2.0.0
  template:
    metadata:
      labels:
        app: a3028-zero-dtd-test
        version: 2.0.0
    spec:
      containers:
      - name: a3028-app
        image: amdp-registry.skala-ai.com/skala26a-ai1/a3028-my-app:v2
        ports:
        - containerPort: 8080