apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a3028-app-ingress        # 이름: v1 전용
  namespace: skala3-ai1
spec:
  ingressClassName: public-nginx
  rules:
  - host: a3028.project.skala-ai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: a3028-app-service   # 기존 v1 서비스 이름
            port:
              number: 8080            # 포트 번호 확인!