apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk3028-my-pvc
  namespace: skala3-ai1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3